# Setup
title:        陈世泽的博客
tagline:      CHEN SHIZE’S BLOG」
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://chenshize.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown