# Setup
title:        Bolero
tagline:      陈世泽的博客
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       CHEN SHIZE
  url:        http://chenshize.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown