# Setup
title:        Bolero
tagline:      Chen Shize's Blog
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       CHEN SHIZE
  url:        http://chenshize.com 

# Gems
gems:
  - jekyll-paginate
#Others
markdown: kramdown
